USE MASTER;
GO

DROP DATABASE IF EXISTS DriveDB;
GO

CREATE DATABASE DriveDB;
GO

USE DriveDB;
GO

DROP TABLE IF EXISTS UserDrive;

CREATE TABLE UserDrive (
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) NULL,
	Lastname NVARCHAR(100) NULL,
	Username NVARCHAR(100) NOT NULL UNIQUE,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Password NVARCHAR(255) NOT NULL,
);

DROP TABLE IF EXISTS Register;

CREATE TABLE Register (
	Id INT IDENTITY PRIMARY KEY,
	IsFolder BIT NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	FileExtension NVARCHAR(100) NULL,
	pathOrURL NVARCHAR(255) NOT NULL,
	Size INT NULL,
	Author INT NOT NULL REFERENCES UserDrive(Id),
	UploadDate DATETIME NOT NULL,
	LastModifiedDate DATETIME NOT NULL,
	ParentFolder INT NULL FOREIGN KEY REFERENCES Register(Id),
);
GO

INSERT INTO UserDrive VALUES('Admin', 'Super Admin', 'admin07', 'admin@gmail.com', 'A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3');